# Configuração do Perfil de Hardware: Aquário STV3000
BOARD_NAME="Aquário STV3000"
BOARD_MODEL="aquario-stv3000"
SOC_FAMILY="amlogic-s905w"
SOC_MODEL="S905W"
ARCH="arm64"

# Parâmetros do Android
ANDROID_VERSION="9"
ANDROID_BUILD_TYPE="userdebug"
AOSP_DEVICE_TREE="device/amlogic/stv3000"

# Parâmetros de Memória & Kernel
KERNEL_VERSION="4.9.113"
KERNEL_DEFCONFIG="stv3000_defconfig"
CMA_SIZE_MB="224"
CMA_NAME="codec_mm_cma"
GPIO_LED_STANDBY="474" # GPIODV_24

# Parâmetros do Bootloader U-Boot
UBOOT_TARGET="gxl_p281_v1"
UBOOT_HANDOFF_DOT="1"
SD_FAILFAST_FIX="1"

# Layout de Partições
PARTITION_TABLE="ept_stv3000_14part.json"
SYSTEM_PART_SIZE_MB="1700"
